################################################################
# Dockerfile to build personal devellopment workstations images
#
# Based on CentOS 6.9
################################################################

FROM centos:6.9
MAINTAINER ericlichen
RUN yum update -y

############### Add Necessary Repo Files ######################
RUN yum install epel-release -y
